sudo: required
dist: trusty

language: c

compiler:
  - gcc
python:
  - "3.3"

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('vagrant') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script: "sudo bash ./scripts/travis-build.sh"


