
language: c

compiler:
  - gcc
python:
  - "3.3"

install: "pip install -r requirements.txt"

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('vagrant') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script: "sudo bash ./scripts/freeciv-web-travis.sh"


